name: clinica-prod

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile

    container_name: clinica-api
    restart: unless-stopped

    expose:
      - "8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Production

      ConnectionStrings__DefaultConnection: ${CONNECTION_STRING:-Server=host.docker.internal,1433;Database=ClinicaDb;User Id=sa;Password=YourSecurePasswordHere!;TrustServerCertificate=True;}

      Cors__AllowedOrigins__0: http://157.173.99.216:8084

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - infraestructura-network

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://157.173.99.216:5011/api/v1}

    container_name: clinica-web
    restart: unless-stopped

    expose:
      - "3000"

    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://157.173.99.216:5011/api/v1}

    depends_on:
      - api

    networks:
      - infraestructura-network

networks:
  infraestructura-network:
    external: true
