namespace Clinica.Modules.RecursosHumanos.Infrastructure.Seed;

internal static class RecursosHumanosCatalogSeedData
{
    internal static readonly (string Codigo, string Nombre, int Orden)[] TiposArea =
    [
        ("ORG", "Organización", 1),
        ("DIR", "Dirección", 2),
        ("ARE", "Área", 3),
        ("DEP", "Departamento", 4),
        ("SER", "Servicio", 5)
    ];

    internal static readonly string[] Cargos =
    [
        "Administrador",
        "Anestesiología",
        "Anestesiólogo",
        "Archivista",
        "Auxiliar Administrativo",
        "Auxiliar Administrativo de Caja",
        "Auxiliar de Caja y Seguros",
        "Auxiliar de Enfermería",
        "Auxiliar de Enfermería de Apoyo",
        "Auxiliar de Farmacia",
        "Auxiliar de Laboratorio",
        "Auxiliar de Marketing y Admisión",
        "Ayudante de Cocina",
        "Ayudante de Lavado",
        "Ayudante de Limpieza",
        "Cajas",
        "Cajas y Tesorería",
        "Cajero",
        "Cardiología",
        "Circulante",
        "Cirugía General",
        "Cirugía Plástica",
        "Colposcopia",
        "Contador",
        "Director General",
        "Director Médico",
        "Ecografista",
        "Encargado de Cocina",
        "Encargado de Costura",
        "Encargado de Esterilización",
        "Encargado de Limpieza",
        "Encargado de Mantenimiento",
        "Encargado de Neonatología",
        "Encargado de Planchado",
        "Encargado de Quirófano",
        "Encargado de Rayos X",
        "Encargado de Servicio",
        "Encargado de UTI",
        "Enfermero de Base",
        "Enfermero de Emergencias",
        "Enfermero de Esterilización",
        "Enfermero de Quirófano",
        "Enfermero de Salas de Internación",
        "Enfermero de Servicio Crítico",
        "Estadígrafo",
        "Esterilización",
        "Farmacia",
        "Gastroenterología",
        "Gerente Administrativo",
        "Gerente Administrativo Financiero",
        "Geriatría",
        "Ginecología",
        "Guardia de Seguridad / Portero",
        "Instrumentista",
        "Instrumentista Quirúrgico",
        "Jefe de Enfermería",
        "Laboratorios",
        "Lavado y Planchado",
        "Limpieza",
        "Marketing",
        "Medicina Crítica y Terapia Intensiva",
        "Medicina Interna",
        "Médico",
        "Médico de Guardia",
        "Médico General de Guardia",
        "Otorrinolaringología",
        "Pediatría",
        "Personal de Esterilización",
        "Planchado",
        "Psiquiatra",
        "Psiquiatría",
        "Quirófano",
        "Radiólogo",
        "Recepcionista",
        "Regente de Farmacia",
        "Responsable",
        "Responsable de Esterilización",
        "Responsable de Quirófano",
        "Supervisor de Enfermería",
        "Técnico en Rayos X",
        "Terapia Intensiva",
        "Traumatología",
        "Traumatólogo",
        "Urólogo"
    ];

    internal static readonly string[] Profesiones =
    [
        "Anestesiólogo",
        "Auxiliar de Enfermería",
        "Auxiliar de Laboratorio",
        "Bachiller",
        "Bioquímico",
        "Bioquímico Farmacéutico",
        "Cardiólogo",
        "Cirujano General",
        "Cirujano Geriatra",
        "Cirujano Plástico",
        "Contador",
        "Gastroenterólogo",
        "Ginecólogo",
        "Ginecólogo Obstetra",
        "Hematólogo",
        "Imagenólogo",
        "Ingeniero Comercial",
        "Laboratorista",
        "Licenciado en Contaduría Pública",
        "Licenciado en Enfermería",
        "Médico General",
        "Médico General Dermatoestético",
        "Médico Intensivista",
        "Médico Internista",
        "Neurocirujano",
        "Nutricionista",
        "Otorrinolaringólogo",
        "Pediatra",
        "Pediatra Neonatólogo",
        "Psiquiatra",
        "Reumatólogo",
        "Secretaria Ejecutiva",
        "Técnico de Laboratorio",
        "Técnico en Enfermería",
        "Técnico en Radiología",
        "Técnico Medio",
        "Técnico Medio en Enfermería",
        "Traumatólogo",
        "Urólogo"
    ];

    internal static readonly string[] Especialidades =
    [
        "Anestesiología",
        "Cardiología",
        "Cirugía General",
        "Cirugía Plástica, Estética y Reconstructiva",
        "Ecografía",
        "Farmacia",
        "Gastroenterología",
        "Geriatría",
        "Ginecología y Obstetricia",
        "Hematología",
        "Imagenología",
        "Laboratorio Clínico",
        "Medicina Crítica y Terapia Intensiva",
        "Medicina Dermatoestética",
        "Medicina Interna",
        "Neonatología",
        "Neurocirugía",
        "Nutrición Clínica",
        "Otorrinolaringología",
        "Pediatría",
        "Psiquiatría",
        "Radiología",
        "Reumatología",
        "Traumatología",
        "Urología"
    ];
}
