import type { ComponentType, CSSProperties } from 'react'
import {
    AimOutlined,
    AlertOutlined,
    ApartmentOutlined,
    AppstoreOutlined,
    AuditOutlined,
    BankOutlined,
    BellOutlined,
    BookOutlined,
    BuildOutlined,
    CalendarOutlined,
    CameraOutlined,
    CarOutlined,
    CarryOutOutlined,
    ClockCircleOutlined,
    ClusterOutlined,
    CompassOutlined,
    ContactsOutlined,
    ControlOutlined,
    CustomerServiceOutlined,
    DashboardOutlined,
    DatabaseOutlined,
    DeploymentUnitOutlined,
    EnvironmentOutlined,
    ExperimentOutlined,
    EyeOutlined,
    FieldTimeOutlined,
    FileProtectOutlined,
    FileSearchOutlined,
    FileTextOutlined,
    FireOutlined,
    FlagOutlined,
    FormOutlined,
    HeartOutlined,
    HistoryOutlined,
    HomeOutlined,
    HourglassOutlined,
    IdcardOutlined,
    InsuranceOutlined,
    MedicineBoxOutlined,
    MonitorOutlined,
    NodeIndexOutlined,
    NotificationOutlined,
    PartitionOutlined,
    PhoneOutlined,
    ProfileOutlined,
    ReadOutlined,
    ReconciliationOutlined,
    SafetyCertificateOutlined,
    ScanOutlined,
    ScheduleOutlined,
    SolutionOutlined,
    StarOutlined,
    TeamOutlined,
    ThunderboltOutlined,
    ToolOutlined,
    UserAddOutlined,
    UserOutlined,
    VideoCameraOutlined,
    WarningOutlined,
} from '@ant-design/icons'

export type TipoAtencionIconOption = {
    value: string
    label: string
    Icon: ComponentType<{ style?: CSSProperties; className?: string }>
}

export const TIPO_ATENCION_ICON_OPTIONS: TipoAtencionIconOption[] = [
    { value: 'MedicineBoxOutlined', label: 'Medicina', Icon: MedicineBoxOutlined },
    { value: 'HeartOutlined', label: 'Corazón', Icon: HeartOutlined },
    { value: 'AlertOutlined', label: 'Alerta', Icon: AlertOutlined },
    { value: 'WarningOutlined', label: 'Advertencia', Icon: WarningOutlined },
    { value: 'FireOutlined', label: 'Urgencia', Icon: FireOutlined },
    { value: 'ThunderboltOutlined', label: 'Emergencia', Icon: ThunderboltOutlined },
    { value: 'CarOutlined', label: 'Traslado', Icon: CarOutlined },
    { value: 'HomeOutlined', label: 'Internación', Icon: HomeOutlined },
    { value: 'ApartmentOutlined', label: 'Área', Icon: ApartmentOutlined },
    { value: 'BankOutlined', label: 'Institución', Icon: BankOutlined },
    { value: 'BuildOutlined', label: 'Edificio', Icon: BuildOutlined },
    { value: 'EnvironmentOutlined', label: 'Ubicación', Icon: EnvironmentOutlined },
    { value: 'UserOutlined', label: 'Paciente', Icon: UserOutlined },
    { value: 'UserAddOutlined', label: 'Nuevo paciente', Icon: UserAddOutlined },
    { value: 'TeamOutlined', label: 'Equipo', Icon: TeamOutlined },
    { value: 'ContactsOutlined', label: 'Contactos', Icon: ContactsOutlined },
    { value: 'IdcardOutlined', label: 'Identificación', Icon: IdcardOutlined },
    { value: 'SolutionOutlined', label: 'Consulta', Icon: SolutionOutlined },
    { value: 'AuditOutlined', label: 'Evaluación', Icon: AuditOutlined },
    { value: 'ReconciliationOutlined', label: 'Conciliación', Icon: ReconciliationOutlined },
    { value: 'ProfileOutlined', label: 'Perfil', Icon: ProfileOutlined },
    { value: 'ExperimentOutlined', label: 'Laboratorio', Icon: ExperimentOutlined },
    { value: 'EyeOutlined', label: 'Exploración', Icon: EyeOutlined },
    { value: 'ScanOutlined', label: 'Escaneo', Icon: ScanOutlined },
    { value: 'MonitorOutlined', label: 'Monitoreo', Icon: MonitorOutlined },
    { value: 'DashboardOutlined', label: 'Panel', Icon: DashboardOutlined },
    { value: 'ControlOutlined', label: 'Control', Icon: ControlOutlined },
    { value: 'AimOutlined', label: 'Objetivo', Icon: AimOutlined },
    { value: 'CompassOutlined', label: 'Orientación', Icon: CompassOutlined },
    { value: 'ClusterOutlined', label: 'Unidad', Icon: ClusterOutlined },
    { value: 'DeploymentUnitOutlined', label: 'Servicio', Icon: DeploymentUnitOutlined },
    { value: 'PartitionOutlined', label: 'Sección', Icon: PartitionOutlined },
    { value: 'NodeIndexOutlined', label: 'Flujo', Icon: NodeIndexOutlined },
    { value: 'AppstoreOutlined', label: 'Módulos', Icon: AppstoreOutlined },
    { value: 'CalendarOutlined', label: 'Cita', Icon: CalendarOutlined },
    { value: 'ScheduleOutlined', label: 'Agenda', Icon: ScheduleOutlined },
    { value: 'CarryOutOutlined', label: 'Procedimiento', Icon: CarryOutOutlined },
    { value: 'ClockCircleOutlined', label: 'Turno', Icon: ClockCircleOutlined },
    { value: 'FieldTimeOutlined', label: 'Tiempo', Icon: FieldTimeOutlined },
    { value: 'HistoryOutlined', label: 'Historórico', Icon: HistoryOutlined },
    { value: 'HourglassOutlined', label: 'Espera', Icon: HourglassOutlined },
    { value: 'FileTextOutlined', label: 'Historia', Icon: FileTextOutlined },
    { value: 'FileSearchOutlined', label: 'Revisión', Icon: FileSearchOutlined },
    { value: 'FileProtectOutlined', label: 'Registro', Icon: FileProtectOutlined },
    { value: 'FormOutlined', label: 'Formulario', Icon: FormOutlined },
    { value: 'BookOutlined', label: 'Manual', Icon: BookOutlined },
    { value: 'ReadOutlined', label: 'Lectura', Icon: ReadOutlined },
    { value: 'DatabaseOutlined', label: 'Datos', Icon: DatabaseOutlined },
    { value: 'SafetyCertificateOutlined', label: 'Seguridad', Icon: SafetyCertificateOutlined },
    { value: 'InsuranceOutlined', label: 'Seguro', Icon: InsuranceOutlined },
    { value: 'PhoneOutlined', label: 'Llamada', Icon: PhoneOutlined },
    { value: 'CustomerServiceOutlined', label: 'Atención', Icon: CustomerServiceOutlined },
    { value: 'BellOutlined', label: 'Aviso', Icon: BellOutlined },
    { value: 'NotificationOutlined', label: 'Notificación', Icon: NotificationOutlined },
    { value: 'FlagOutlined', label: 'Prioridad', Icon: FlagOutlined },
    { value: 'StarOutlined', label: 'Destacado', Icon: StarOutlined },
    { value: 'CameraOutlined', label: 'Imagen', Icon: CameraOutlined },
    { value: 'VideoCameraOutlined', label: 'Video', Icon: VideoCameraOutlined },
    { value: 'ToolOutlined', label: 'Instrumental', Icon: ToolOutlined },
]

const iconByValue = new Map(
    TIPO_ATENCION_ICON_OPTIONS.map((option) => [option.value, option]),
)

export function getTipoAtencionIcon(icono?: string | null) {
    if (!icono) return MedicineBoxOutlined
    return iconByValue.get(icono)?.Icon ?? MedicineBoxOutlined
}

export function getTipoAtencionIconLabel(icono?: string | null) {
    if (!icono) return 'Medicina'
    return iconByValue.get(icono)?.label ?? icono
}

export const DEFAULT_TIPO_ATENCION_COLOR = '#1677ff'
export const DEFAULT_TIPO_ATENCION_ICONO = 'MedicineBoxOutlined'
