services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: clinica-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Clinica@2026!"
    ports:
      - "1433:1433"
    volumes:
      - clinica-sqlserver-data:/var/opt/mssql
    restart: unless-stopped

volumes:
  clinica-sqlserver-data:
