/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AdminSeguridadRouteImport } from './routes/_admin/seguridad'
import { Route as AdminRecursosHumanosRouteImport } from './routes/_admin/recursos-humanos'
import { Route as AdminParametrosRouteImport } from './routes/_admin/parametros'
import { Route as AdminLaboratorioRouteImport } from './routes/_admin/laboratorio'
import { Route as AdminAtencionesRouteImport } from './routes/_admin/atenciones'
import { Route as AdminWorkflowIndexRouteImport } from './routes/_admin/workflow/index'
import { Route as AdminUsuariosIndexRouteImport } from './routes/_admin/usuarios/index'
import { Route as AdminSeguridadIndexRouteImport } from './routes/_admin/seguridad/index'
import { Route as AdminRolesIndexRouteImport } from './routes/_admin/roles/index'
import { Route as AdminRecursosHumanosIndexRouteImport } from './routes/_admin/recursos-humanos/index'
import { Route as AdminPersonasIndexRouteImport } from './routes/_admin/personas/index'
import { Route as AdminParametrosIndexRouteImport } from './routes/_admin/parametros/index'
import { Route as AdminPacientesIndexRouteImport } from './routes/_admin/pacientes/index'
import { Route as AdminLaboratorioIndexRouteImport } from './routes/_admin/laboratorio/index'
import { Route as AdminCatalogosIndexRouteImport } from './routes/_admin/catalogos/index'
import { Route as AdminAtencionesIndexRouteImport } from './routes/_admin/atenciones/index'
import { Route as AdminUsuariosPerfilRouteImport } from './routes/_admin/usuarios/perfil'
import { Route as AdminSeguridadUsuariosRouteImport } from './routes/_admin/seguridad/usuarios'
import { Route as AdminSeguridadRolesRouteImport } from './routes/_admin/seguridad/roles'
import { Route as AdminRecursosHumanosProfesionesRouteImport } from './routes/_admin/recursos-humanos/profesiones'
import { Route as AdminRecursosHumanosMedicosRouteImport } from './routes/_admin/recursos-humanos/medicos'
import { Route as AdminRecursosHumanosJerarquiaRouteImport } from './routes/_admin/recursos-humanos/jerarquia'
import { Route as AdminRecursosHumanosEspecialidadesRouteImport } from './routes/_admin/recursos-humanos/especialidades'
import { Route as AdminRecursosHumanosEmpleadosRouteImport } from './routes/_admin/recursos-humanos/empleados'
import { Route as AdminRecursosHumanosCargosRouteImport } from './routes/_admin/recursos-humanos/cargos'
import { Route as AdminParametrosUnidadesMedidaRouteImport } from './routes/_admin/parametros/unidades-medida'
import { Route as AdminParametrosCorrelativosRouteImport } from './routes/_admin/parametros/correlativos'
import { Route as AdminParametrosCatalogosRouteImport } from './routes/_admin/parametros/catalogos'
import { Route as AdminLaboratorioTiposExamenRouteImport } from './routes/_admin/laboratorio/tipos-examen'
import { Route as AdminLaboratorioPruebasRouteImport } from './routes/_admin/laboratorio/pruebas'
import { Route as AdminLaboratorioEspecialidadesRouteImport } from './routes/_admin/laboratorio/especialidades'
import { Route as AdminAtencionesTiposAtencionRouteImport } from './routes/_admin/atenciones/tipos-atencion'
import { Route as AdminAtencionesFormulariosRouteImport } from './routes/_admin/atenciones/formularios'
import { Route as AdminAtencionesAtencionIdRouteImport } from './routes/_admin/atenciones/$atencionId'
import { Route as AdminWorkflowInstancesInstanceIdRouteImport } from './routes/_admin/workflow/instances/$instanceId'
import { Route as AdminWorkflowDesignerDefinitionIdRouteImport } from './routes/_admin/workflow/designer/$definitionId'
import { Route as AdminAtencionesFormulariosTipoAtencionIdRouteImport } from './routes/_admin/atenciones/formularios.$tipoAtencionId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AdminSeguridadRoute = AdminSeguridadRouteImport.update({
  id: '/seguridad',
  path: '/seguridad',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecursosHumanosRoute = AdminRecursosHumanosRouteImport.update({
  id: '/recursos-humanos',
  path: '/recursos-humanos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametrosRoute = AdminParametrosRouteImport.update({
  id: '/parametros',
  path: '/parametros',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLaboratorioRoute = AdminLaboratorioRouteImport.update({
  id: '/laboratorio',
  path: '/laboratorio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAtencionesRoute = AdminAtencionesRouteImport.update({
  id: '/atenciones',
  path: '/atenciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkflowIndexRoute = AdminWorkflowIndexRouteImport.update({
  id: '/workflow/',
  path: '/workflow/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosIndexRoute = AdminUsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeguridadIndexRoute = AdminSeguridadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSeguridadRoute,
} as any)
const AdminRolesIndexRoute = AdminRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecursosHumanosIndexRoute =
  AdminRecursosHumanosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminRecursosHumanosRoute,
  } as any)
const AdminPersonasIndexRoute = AdminPersonasIndexRouteImport.update({
  id: '/personas/',
  path: '/personas/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametrosIndexRoute = AdminParametrosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminParametrosRoute,
} as any)
const AdminPacientesIndexRoute = AdminPacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLaboratorioIndexRoute = AdminLaboratorioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLaboratorioRoute,
} as any)
const AdminCatalogosIndexRoute = AdminCatalogosIndexRouteImport.update({
  id: '/catalogos/',
  path: '/catalogos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAtencionesIndexRoute = AdminAtencionesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAtencionesRoute,
} as any)
const AdminUsuariosPerfilRoute = AdminUsuariosPerfilRouteImport.update({
  id: '/usuarios/perfil',
  path: '/usuarios/perfil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeguridadUsuariosRoute = AdminSeguridadUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminSeguridadRoute,
} as any)
const AdminSeguridadRolesRoute = AdminSeguridadRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminSeguridadRoute,
} as any)
const AdminRecursosHumanosProfesionesRoute =
  AdminRecursosHumanosProfesionesRouteImport.update({
    id: '/profesiones',
    path: '/profesiones',
    getParentRoute: () => AdminRecursosHumanosRoute,
  } as any)
const AdminRecursosHumanosMedicosRoute =
  AdminRecursosHumanosMedicosRouteImport.update({
    id: '/medicos',
    path: '/medicos',
    getParentRoute: () => AdminRecursosHumanosRoute,
  } as any)
const AdminRecursosHumanosJerarquiaRoute =
  AdminRecursosHumanosJerarquiaRouteImport.update({
    id: '/jerarquia',
    path: '/jerarquia',
    getParentRoute: () => AdminRecursosHumanosRoute,
  } as any)
const AdminRecursosHumanosEspecialidadesRoute =
  AdminRecursosHumanosEspecialidadesRouteImport.update({
    id: '/especialidades',
    path: '/especialidades',
    getParentRoute: () => AdminRecursosHumanosRoute,
  } as any)
const AdminRecursosHumanosEmpleadosRoute =
  AdminRecursosHumanosEmpleadosRouteImport.update({
    id: '/empleados',
    path: '/empleados',
    getParentRoute: () => AdminRecursosHumanosRoute,
  } as any)
const AdminRecursosHumanosCargosRoute =
  AdminRecursosHumanosCargosRouteImport.update({
    id: '/cargos',
    path: '/cargos',
    getParentRoute: () => AdminRecursosHumanosRoute,
  } as any)
const AdminParametrosUnidadesMedidaRoute =
  AdminParametrosUnidadesMedidaRouteImport.update({
    id: '/unidades-medida',
    path: '/unidades-medida',
    getParentRoute: () => AdminParametrosRoute,
  } as any)
const AdminParametrosCorrelativosRoute =
  AdminParametrosCorrelativosRouteImport.update({
    id: '/correlativos',
    path: '/correlativos',
    getParentRoute: () => AdminParametrosRoute,
  } as any)
const AdminParametrosCatalogosRoute =
  AdminParametrosCatalogosRouteImport.update({
    id: '/catalogos',
    path: '/catalogos',
    getParentRoute: () => AdminParametrosRoute,
  } as any)
const AdminLaboratorioTiposExamenRoute =
  AdminLaboratorioTiposExamenRouteImport.update({
    id: '/tipos-examen',
    path: '/tipos-examen',
    getParentRoute: () => AdminLaboratorioRoute,
  } as any)
const AdminLaboratorioPruebasRoute = AdminLaboratorioPruebasRouteImport.update({
  id: '/pruebas',
  path: '/pruebas',
  getParentRoute: () => AdminLaboratorioRoute,
} as any)
const AdminLaboratorioEspecialidadesRoute =
  AdminLaboratorioEspecialidadesRouteImport.update({
    id: '/especialidades',
    path: '/especialidades',
    getParentRoute: () => AdminLaboratorioRoute,
  } as any)
const AdminAtencionesTiposAtencionRoute =
  AdminAtencionesTiposAtencionRouteImport.update({
    id: '/tipos-atencion',
    path: '/tipos-atencion',
    getParentRoute: () => AdminAtencionesRoute,
  } as any)
const AdminAtencionesFormulariosRoute =
  AdminAtencionesFormulariosRouteImport.update({
    id: '/formularios',
    path: '/formularios',
    getParentRoute: () => AdminAtencionesRoute,
  } as any)
const AdminAtencionesAtencionIdRoute =
  AdminAtencionesAtencionIdRouteImport.update({
    id: '/$atencionId',
    path: '/$atencionId',
    getParentRoute: () => AdminAtencionesRoute,
  } as any)
const AdminWorkflowInstancesInstanceIdRoute =
  AdminWorkflowInstancesInstanceIdRouteImport.update({
    id: '/workflow/instances/$instanceId',
    path: '/workflow/instances/$instanceId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminWorkflowDesignerDefinitionIdRoute =
  AdminWorkflowDesignerDefinitionIdRouteImport.update({
    id: '/workflow/designer/$definitionId',
    path: '/workflow/designer/$definitionId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAtencionesFormulariosTipoAtencionIdRoute =
  AdminAtencionesFormulariosTipoAtencionIdRouteImport.update({
    id: '/$tipoAtencionId',
    path: '/$tipoAtencionId',
    getParentRoute: () => AdminAtencionesFormulariosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/atenciones': typeof AdminAtencionesRouteWithChildren
  '/laboratorio': typeof AdminLaboratorioRouteWithChildren
  '/parametros': typeof AdminParametrosRouteWithChildren
  '/recursos-humanos': typeof AdminRecursosHumanosRouteWithChildren
  '/seguridad': typeof AdminSeguridadRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/atenciones/$atencionId': typeof AdminAtencionesAtencionIdRoute
  '/atenciones/formularios': typeof AdminAtencionesFormulariosRouteWithChildren
  '/atenciones/tipos-atencion': typeof AdminAtencionesTiposAtencionRoute
  '/laboratorio/especialidades': typeof AdminLaboratorioEspecialidadesRoute
  '/laboratorio/pruebas': typeof AdminLaboratorioPruebasRoute
  '/laboratorio/tipos-examen': typeof AdminLaboratorioTiposExamenRoute
  '/parametros/catalogos': typeof AdminParametrosCatalogosRoute
  '/parametros/correlativos': typeof AdminParametrosCorrelativosRoute
  '/parametros/unidades-medida': typeof AdminParametrosUnidadesMedidaRoute
  '/recursos-humanos/cargos': typeof AdminRecursosHumanosCargosRoute
  '/recursos-humanos/empleados': typeof AdminRecursosHumanosEmpleadosRoute
  '/recursos-humanos/especialidades': typeof AdminRecursosHumanosEspecialidadesRoute
  '/recursos-humanos/jerarquia': typeof AdminRecursosHumanosJerarquiaRoute
  '/recursos-humanos/medicos': typeof AdminRecursosHumanosMedicosRoute
  '/recursos-humanos/profesiones': typeof AdminRecursosHumanosProfesionesRoute
  '/seguridad/roles': typeof AdminSeguridadRolesRoute
  '/seguridad/usuarios': typeof AdminSeguridadUsuariosRoute
  '/usuarios/perfil': typeof AdminUsuariosPerfilRoute
  '/atenciones/': typeof AdminAtencionesIndexRoute
  '/catalogos/': typeof AdminCatalogosIndexRoute
  '/laboratorio/': typeof AdminLaboratorioIndexRoute
  '/pacientes/': typeof AdminPacientesIndexRoute
  '/parametros/': typeof AdminParametrosIndexRoute
  '/personas/': typeof AdminPersonasIndexRoute
  '/recursos-humanos/': typeof AdminRecursosHumanosIndexRoute
  '/roles/': typeof AdminRolesIndexRoute
  '/seguridad/': typeof AdminSeguridadIndexRoute
  '/usuarios/': typeof AdminUsuariosIndexRoute
  '/workflow/': typeof AdminWorkflowIndexRoute
  '/atenciones/formularios/$tipoAtencionId': typeof AdminAtencionesFormulariosTipoAtencionIdRoute
  '/workflow/designer/$definitionId': typeof AdminWorkflowDesignerDefinitionIdRoute
  '/workflow/instances/$instanceId': typeof AdminWorkflowInstancesInstanceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AdminIndexRoute
  '/login': typeof AuthLoginRoute
  '/atenciones/$atencionId': typeof AdminAtencionesAtencionIdRoute
  '/atenciones/formularios': typeof AdminAtencionesFormulariosRouteWithChildren
  '/atenciones/tipos-atencion': typeof AdminAtencionesTiposAtencionRoute
  '/laboratorio/especialidades': typeof AdminLaboratorioEspecialidadesRoute
  '/laboratorio/pruebas': typeof AdminLaboratorioPruebasRoute
  '/laboratorio/tipos-examen': typeof AdminLaboratorioTiposExamenRoute
  '/parametros/catalogos': typeof AdminParametrosCatalogosRoute
  '/parametros/correlativos': typeof AdminParametrosCorrelativosRoute
  '/parametros/unidades-medida': typeof AdminParametrosUnidadesMedidaRoute
  '/recursos-humanos/cargos': typeof AdminRecursosHumanosCargosRoute
  '/recursos-humanos/empleados': typeof AdminRecursosHumanosEmpleadosRoute
  '/recursos-humanos/especialidades': typeof AdminRecursosHumanosEspecialidadesRoute
  '/recursos-humanos/jerarquia': typeof AdminRecursosHumanosJerarquiaRoute
  '/recursos-humanos/medicos': typeof AdminRecursosHumanosMedicosRoute
  '/recursos-humanos/profesiones': typeof AdminRecursosHumanosProfesionesRoute
  '/seguridad/roles': typeof AdminSeguridadRolesRoute
  '/seguridad/usuarios': typeof AdminSeguridadUsuariosRoute
  '/usuarios/perfil': typeof AdminUsuariosPerfilRoute
  '/atenciones': typeof AdminAtencionesIndexRoute
  '/catalogos': typeof AdminCatalogosIndexRoute
  '/laboratorio': typeof AdminLaboratorioIndexRoute
  '/pacientes': typeof AdminPacientesIndexRoute
  '/parametros': typeof AdminParametrosIndexRoute
  '/personas': typeof AdminPersonasIndexRoute
  '/recursos-humanos': typeof AdminRecursosHumanosIndexRoute
  '/roles': typeof AdminRolesIndexRoute
  '/seguridad': typeof AdminSeguridadIndexRoute
  '/usuarios': typeof AdminUsuariosIndexRoute
  '/workflow': typeof AdminWorkflowIndexRoute
  '/atenciones/formularios/$tipoAtencionId': typeof AdminAtencionesFormulariosTipoAtencionIdRoute
  '/workflow/designer/$definitionId': typeof AdminWorkflowDesignerDefinitionIdRoute
  '/workflow/instances/$instanceId': typeof AdminWorkflowInstancesInstanceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_admin/atenciones': typeof AdminAtencionesRouteWithChildren
  '/_admin/laboratorio': typeof AdminLaboratorioRouteWithChildren
  '/_admin/parametros': typeof AdminParametrosRouteWithChildren
  '/_admin/recursos-humanos': typeof AdminRecursosHumanosRouteWithChildren
  '/_admin/seguridad': typeof AdminSeguridadRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/atenciones/$atencionId': typeof AdminAtencionesAtencionIdRoute
  '/_admin/atenciones/formularios': typeof AdminAtencionesFormulariosRouteWithChildren
  '/_admin/atenciones/tipos-atencion': typeof AdminAtencionesTiposAtencionRoute
  '/_admin/laboratorio/especialidades': typeof AdminLaboratorioEspecialidadesRoute
  '/_admin/laboratorio/pruebas': typeof AdminLaboratorioPruebasRoute
  '/_admin/laboratorio/tipos-examen': typeof AdminLaboratorioTiposExamenRoute
  '/_admin/parametros/catalogos': typeof AdminParametrosCatalogosRoute
  '/_admin/parametros/correlativos': typeof AdminParametrosCorrelativosRoute
  '/_admin/parametros/unidades-medida': typeof AdminParametrosUnidadesMedidaRoute
  '/_admin/recursos-humanos/cargos': typeof AdminRecursosHumanosCargosRoute
  '/_admin/recursos-humanos/empleados': typeof AdminRecursosHumanosEmpleadosRoute
  '/_admin/recursos-humanos/especialidades': typeof AdminRecursosHumanosEspecialidadesRoute
  '/_admin/recursos-humanos/jerarquia': typeof AdminRecursosHumanosJerarquiaRoute
  '/_admin/recursos-humanos/medicos': typeof AdminRecursosHumanosMedicosRoute
  '/_admin/recursos-humanos/profesiones': typeof AdminRecursosHumanosProfesionesRoute
  '/_admin/seguridad/roles': typeof AdminSeguridadRolesRoute
  '/_admin/seguridad/usuarios': typeof AdminSeguridadUsuariosRoute
  '/_admin/usuarios/perfil': typeof AdminUsuariosPerfilRoute
  '/_admin/atenciones/': typeof AdminAtencionesIndexRoute
  '/_admin/catalogos/': typeof AdminCatalogosIndexRoute
  '/_admin/laboratorio/': typeof AdminLaboratorioIndexRoute
  '/_admin/pacientes/': typeof AdminPacientesIndexRoute
  '/_admin/parametros/': typeof AdminParametrosIndexRoute
  '/_admin/personas/': typeof AdminPersonasIndexRoute
  '/_admin/recursos-humanos/': typeof AdminRecursosHumanosIndexRoute
  '/_admin/roles/': typeof AdminRolesIndexRoute
  '/_admin/seguridad/': typeof AdminSeguridadIndexRoute
  '/_admin/usuarios/': typeof AdminUsuariosIndexRoute
  '/_admin/workflow/': typeof AdminWorkflowIndexRoute
  '/_admin/atenciones/formularios/$tipoAtencionId': typeof AdminAtencionesFormulariosTipoAtencionIdRoute
  '/_admin/workflow/designer/$definitionId': typeof AdminWorkflowDesignerDefinitionIdRoute
  '/_admin/workflow/instances/$instanceId': typeof AdminWorkflowInstancesInstanceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atenciones'
    | '/laboratorio'
    | '/parametros'
    | '/recursos-humanos'
    | '/seguridad'
    | '/login'
    | '/atenciones/$atencionId'
    | '/atenciones/formularios'
    | '/atenciones/tipos-atencion'
    | '/laboratorio/especialidades'
    | '/laboratorio/pruebas'
    | '/laboratorio/tipos-examen'
    | '/parametros/catalogos'
    | '/parametros/correlativos'
    | '/parametros/unidades-medida'
    | '/recursos-humanos/cargos'
    | '/recursos-humanos/empleados'
    | '/recursos-humanos/especialidades'
    | '/recursos-humanos/jerarquia'
    | '/recursos-humanos/medicos'
    | '/recursos-humanos/profesiones'
    | '/seguridad/roles'
    | '/seguridad/usuarios'
    | '/usuarios/perfil'
    | '/atenciones/'
    | '/catalogos/'
    | '/laboratorio/'
    | '/pacientes/'
    | '/parametros/'
    | '/personas/'
    | '/recursos-humanos/'
    | '/roles/'
    | '/seguridad/'
    | '/usuarios/'
    | '/workflow/'
    | '/atenciones/formularios/$tipoAtencionId'
    | '/workflow/designer/$definitionId'
    | '/workflow/instances/$instanceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/atenciones/$atencionId'
    | '/atenciones/formularios'
    | '/atenciones/tipos-atencion'
    | '/laboratorio/especialidades'
    | '/laboratorio/pruebas'
    | '/laboratorio/tipos-examen'
    | '/parametros/catalogos'
    | '/parametros/correlativos'
    | '/parametros/unidades-medida'
    | '/recursos-humanos/cargos'
    | '/recursos-humanos/empleados'
    | '/recursos-humanos/especialidades'
    | '/recursos-humanos/jerarquia'
    | '/recursos-humanos/medicos'
    | '/recursos-humanos/profesiones'
    | '/seguridad/roles'
    | '/seguridad/usuarios'
    | '/usuarios/perfil'
    | '/atenciones'
    | '/catalogos'
    | '/laboratorio'
    | '/pacientes'
    | '/parametros'
    | '/personas'
    | '/recursos-humanos'
    | '/roles'
    | '/seguridad'
    | '/usuarios'
    | '/workflow'
    | '/atenciones/formularios/$tipoAtencionId'
    | '/workflow/designer/$definitionId'
    | '/workflow/instances/$instanceId'
  id:
    | '__root__'
    | '/_admin'
    | '/_auth'
    | '/_admin/atenciones'
    | '/_admin/laboratorio'
    | '/_admin/parametros'
    | '/_admin/recursos-humanos'
    | '/_admin/seguridad'
    | '/_auth/login'
    | '/_admin/'
    | '/_admin/atenciones/$atencionId'
    | '/_admin/atenciones/formularios'
    | '/_admin/atenciones/tipos-atencion'
    | '/_admin/laboratorio/especialidades'
    | '/_admin/laboratorio/pruebas'
    | '/_admin/laboratorio/tipos-examen'
    | '/_admin/parametros/catalogos'
    | '/_admin/parametros/correlativos'
    | '/_admin/parametros/unidades-medida'
    | '/_admin/recursos-humanos/cargos'
    | '/_admin/recursos-humanos/empleados'
    | '/_admin/recursos-humanos/especialidades'
    | '/_admin/recursos-humanos/jerarquia'
    | '/_admin/recursos-humanos/medicos'
    | '/_admin/recursos-humanos/profesiones'
    | '/_admin/seguridad/roles'
    | '/_admin/seguridad/usuarios'
    | '/_admin/usuarios/perfil'
    | '/_admin/atenciones/'
    | '/_admin/catalogos/'
    | '/_admin/laboratorio/'
    | '/_admin/pacientes/'
    | '/_admin/parametros/'
    | '/_admin/personas/'
    | '/_admin/recursos-humanos/'
    | '/_admin/roles/'
    | '/_admin/seguridad/'
    | '/_admin/usuarios/'
    | '/_admin/workflow/'
    | '/_admin/atenciones/formularios/$tipoAtencionId'
    | '/_admin/workflow/designer/$definitionId'
    | '/_admin/workflow/instances/$instanceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/seguridad': {
      id: '/_admin/seguridad'
      path: '/seguridad'
      fullPath: '/seguridad'
      preLoaderRoute: typeof AdminSeguridadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/recursos-humanos': {
      id: '/_admin/recursos-humanos'
      path: '/recursos-humanos'
      fullPath: '/recursos-humanos'
      preLoaderRoute: typeof AdminRecursosHumanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/parametros': {
      id: '/_admin/parametros'
      path: '/parametros'
      fullPath: '/parametros'
      preLoaderRoute: typeof AdminParametrosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/laboratorio': {
      id: '/_admin/laboratorio'
      path: '/laboratorio'
      fullPath: '/laboratorio'
      preLoaderRoute: typeof AdminLaboratorioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/atenciones': {
      id: '/_admin/atenciones'
      path: '/atenciones'
      fullPath: '/atenciones'
      preLoaderRoute: typeof AdminAtencionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/workflow/': {
      id: '/_admin/workflow/'
      path: '/workflow'
      fullPath: '/workflow/'
      preLoaderRoute: typeof AdminWorkflowIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/usuarios/': {
      id: '/_admin/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof AdminUsuariosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/seguridad/': {
      id: '/_admin/seguridad/'
      path: '/'
      fullPath: '/seguridad/'
      preLoaderRoute: typeof AdminSeguridadIndexRouteImport
      parentRoute: typeof AdminSeguridadRoute
    }
    '/_admin/roles/': {
      id: '/_admin/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AdminRolesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/recursos-humanos/': {
      id: '/_admin/recursos-humanos/'
      path: '/'
      fullPath: '/recursos-humanos/'
      preLoaderRoute: typeof AdminRecursosHumanosIndexRouteImport
      parentRoute: typeof AdminRecursosHumanosRoute
    }
    '/_admin/personas/': {
      id: '/_admin/personas/'
      path: '/personas'
      fullPath: '/personas/'
      preLoaderRoute: typeof AdminPersonasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/parametros/': {
      id: '/_admin/parametros/'
      path: '/'
      fullPath: '/parametros/'
      preLoaderRoute: typeof AdminParametrosIndexRouteImport
      parentRoute: typeof AdminParametrosRoute
    }
    '/_admin/pacientes/': {
      id: '/_admin/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof AdminPacientesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/laboratorio/': {
      id: '/_admin/laboratorio/'
      path: '/'
      fullPath: '/laboratorio/'
      preLoaderRoute: typeof AdminLaboratorioIndexRouteImport
      parentRoute: typeof AdminLaboratorioRoute
    }
    '/_admin/catalogos/': {
      id: '/_admin/catalogos/'
      path: '/catalogos'
      fullPath: '/catalogos/'
      preLoaderRoute: typeof AdminCatalogosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/atenciones/': {
      id: '/_admin/atenciones/'
      path: '/'
      fullPath: '/atenciones/'
      preLoaderRoute: typeof AdminAtencionesIndexRouteImport
      parentRoute: typeof AdminAtencionesRoute
    }
    '/_admin/usuarios/perfil': {
      id: '/_admin/usuarios/perfil'
      path: '/usuarios/perfil'
      fullPath: '/usuarios/perfil'
      preLoaderRoute: typeof AdminUsuariosPerfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/seguridad/usuarios': {
      id: '/_admin/seguridad/usuarios'
      path: '/usuarios'
      fullPath: '/seguridad/usuarios'
      preLoaderRoute: typeof AdminSeguridadUsuariosRouteImport
      parentRoute: typeof AdminSeguridadRoute
    }
    '/_admin/seguridad/roles': {
      id: '/_admin/seguridad/roles'
      path: '/roles'
      fullPath: '/seguridad/roles'
      preLoaderRoute: typeof AdminSeguridadRolesRouteImport
      parentRoute: typeof AdminSeguridadRoute
    }
    '/_admin/recursos-humanos/profesiones': {
      id: '/_admin/recursos-humanos/profesiones'
      path: '/profesiones'
      fullPath: '/recursos-humanos/profesiones'
      preLoaderRoute: typeof AdminRecursosHumanosProfesionesRouteImport
      parentRoute: typeof AdminRecursosHumanosRoute
    }
    '/_admin/recursos-humanos/medicos': {
      id: '/_admin/recursos-humanos/medicos'
      path: '/medicos'
      fullPath: '/recursos-humanos/medicos'
      preLoaderRoute: typeof AdminRecursosHumanosMedicosRouteImport
      parentRoute: typeof AdminRecursosHumanosRoute
    }
    '/_admin/recursos-humanos/jerarquia': {
      id: '/_admin/recursos-humanos/jerarquia'
      path: '/jerarquia'
      fullPath: '/recursos-humanos/jerarquia'
      preLoaderRoute: typeof AdminRecursosHumanosJerarquiaRouteImport
      parentRoute: typeof AdminRecursosHumanosRoute
    }
    '/_admin/recursos-humanos/especialidades': {
      id: '/_admin/recursos-humanos/especialidades'
      path: '/especialidades'
      fullPath: '/recursos-humanos/especialidades'
      preLoaderRoute: typeof AdminRecursosHumanosEspecialidadesRouteImport
      parentRoute: typeof AdminRecursosHumanosRoute
    }
    '/_admin/recursos-humanos/empleados': {
      id: '/_admin/recursos-humanos/empleados'
      path: '/empleados'
      fullPath: '/recursos-humanos/empleados'
      preLoaderRoute: typeof AdminRecursosHumanosEmpleadosRouteImport
      parentRoute: typeof AdminRecursosHumanosRoute
    }
    '/_admin/recursos-humanos/cargos': {
      id: '/_admin/recursos-humanos/cargos'
      path: '/cargos'
      fullPath: '/recursos-humanos/cargos'
      preLoaderRoute: typeof AdminRecursosHumanosCargosRouteImport
      parentRoute: typeof AdminRecursosHumanosRoute
    }
    '/_admin/parametros/unidades-medida': {
      id: '/_admin/parametros/unidades-medida'
      path: '/unidades-medida'
      fullPath: '/parametros/unidades-medida'
      preLoaderRoute: typeof AdminParametrosUnidadesMedidaRouteImport
      parentRoute: typeof AdminParametrosRoute
    }
    '/_admin/parametros/correlativos': {
      id: '/_admin/parametros/correlativos'
      path: '/correlativos'
      fullPath: '/parametros/correlativos'
      preLoaderRoute: typeof AdminParametrosCorrelativosRouteImport
      parentRoute: typeof AdminParametrosRoute
    }
    '/_admin/parametros/catalogos': {
      id: '/_admin/parametros/catalogos'
      path: '/catalogos'
      fullPath: '/parametros/catalogos'
      preLoaderRoute: typeof AdminParametrosCatalogosRouteImport
      parentRoute: typeof AdminParametrosRoute
    }
    '/_admin/laboratorio/tipos-examen': {
      id: '/_admin/laboratorio/tipos-examen'
      path: '/tipos-examen'
      fullPath: '/laboratorio/tipos-examen'
      preLoaderRoute: typeof AdminLaboratorioTiposExamenRouteImport
      parentRoute: typeof AdminLaboratorioRoute
    }
    '/_admin/laboratorio/pruebas': {
      id: '/_admin/laboratorio/pruebas'
      path: '/pruebas'
      fullPath: '/laboratorio/pruebas'
      preLoaderRoute: typeof AdminLaboratorioPruebasRouteImport
      parentRoute: typeof AdminLaboratorioRoute
    }
    '/_admin/laboratorio/especialidades': {
      id: '/_admin/laboratorio/especialidades'
      path: '/especialidades'
      fullPath: '/laboratorio/especialidades'
      preLoaderRoute: typeof AdminLaboratorioEspecialidadesRouteImport
      parentRoute: typeof AdminLaboratorioRoute
    }
    '/_admin/atenciones/tipos-atencion': {
      id: '/_admin/atenciones/tipos-atencion'
      path: '/tipos-atencion'
      fullPath: '/atenciones/tipos-atencion'
      preLoaderRoute: typeof AdminAtencionesTiposAtencionRouteImport
      parentRoute: typeof AdminAtencionesRoute
    }
    '/_admin/atenciones/formularios': {
      id: '/_admin/atenciones/formularios'
      path: '/formularios'
      fullPath: '/atenciones/formularios'
      preLoaderRoute: typeof AdminAtencionesFormulariosRouteImport
      parentRoute: typeof AdminAtencionesRoute
    }
    '/_admin/atenciones/$atencionId': {
      id: '/_admin/atenciones/$atencionId'
      path: '/$atencionId'
      fullPath: '/atenciones/$atencionId'
      preLoaderRoute: typeof AdminAtencionesAtencionIdRouteImport
      parentRoute: typeof AdminAtencionesRoute
    }
    '/_admin/workflow/instances/$instanceId': {
      id: '/_admin/workflow/instances/$instanceId'
      path: '/workflow/instances/$instanceId'
      fullPath: '/workflow/instances/$instanceId'
      preLoaderRoute: typeof AdminWorkflowInstancesInstanceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/workflow/designer/$definitionId': {
      id: '/_admin/workflow/designer/$definitionId'
      path: '/workflow/designer/$definitionId'
      fullPath: '/workflow/designer/$definitionId'
      preLoaderRoute: typeof AdminWorkflowDesignerDefinitionIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/atenciones/formularios/$tipoAtencionId': {
      id: '/_admin/atenciones/formularios/$tipoAtencionId'
      path: '/$tipoAtencionId'
      fullPath: '/atenciones/formularios/$tipoAtencionId'
      preLoaderRoute: typeof AdminAtencionesFormulariosTipoAtencionIdRouteImport
      parentRoute: typeof AdminAtencionesFormulariosRoute
    }
  }
}

interface AdminAtencionesFormulariosRouteChildren {
  AdminAtencionesFormulariosTipoAtencionIdRoute: typeof AdminAtencionesFormulariosTipoAtencionIdRoute
}

const AdminAtencionesFormulariosRouteChildren: AdminAtencionesFormulariosRouteChildren =
  {
    AdminAtencionesFormulariosTipoAtencionIdRoute:
      AdminAtencionesFormulariosTipoAtencionIdRoute,
  }

const AdminAtencionesFormulariosRouteWithChildren =
  AdminAtencionesFormulariosRoute._addFileChildren(
    AdminAtencionesFormulariosRouteChildren,
  )

interface AdminAtencionesRouteChildren {
  AdminAtencionesAtencionIdRoute: typeof AdminAtencionesAtencionIdRoute
  AdminAtencionesFormulariosRoute: typeof AdminAtencionesFormulariosRouteWithChildren
  AdminAtencionesTiposAtencionRoute: typeof AdminAtencionesTiposAtencionRoute
  AdminAtencionesIndexRoute: typeof AdminAtencionesIndexRoute
}

const AdminAtencionesRouteChildren: AdminAtencionesRouteChildren = {
  AdminAtencionesAtencionIdRoute: AdminAtencionesAtencionIdRoute,
  AdminAtencionesFormulariosRoute: AdminAtencionesFormulariosRouteWithChildren,
  AdminAtencionesTiposAtencionRoute: AdminAtencionesTiposAtencionRoute,
  AdminAtencionesIndexRoute: AdminAtencionesIndexRoute,
}

const AdminAtencionesRouteWithChildren = AdminAtencionesRoute._addFileChildren(
  AdminAtencionesRouteChildren,
)

interface AdminLaboratorioRouteChildren {
  AdminLaboratorioEspecialidadesRoute: typeof AdminLaboratorioEspecialidadesRoute
  AdminLaboratorioPruebasRoute: typeof AdminLaboratorioPruebasRoute
  AdminLaboratorioTiposExamenRoute: typeof AdminLaboratorioTiposExamenRoute
  AdminLaboratorioIndexRoute: typeof AdminLaboratorioIndexRoute
}

const AdminLaboratorioRouteChildren: AdminLaboratorioRouteChildren = {
  AdminLaboratorioEspecialidadesRoute: AdminLaboratorioEspecialidadesRoute,
  AdminLaboratorioPruebasRoute: AdminLaboratorioPruebasRoute,
  AdminLaboratorioTiposExamenRoute: AdminLaboratorioTiposExamenRoute,
  AdminLaboratorioIndexRoute: AdminLaboratorioIndexRoute,
}

const AdminLaboratorioRouteWithChildren =
  AdminLaboratorioRoute._addFileChildren(AdminLaboratorioRouteChildren)

interface AdminParametrosRouteChildren {
  AdminParametrosCatalogosRoute: typeof AdminParametrosCatalogosRoute
  AdminParametrosCorrelativosRoute: typeof AdminParametrosCorrelativosRoute
  AdminParametrosUnidadesMedidaRoute: typeof AdminParametrosUnidadesMedidaRoute
  AdminParametrosIndexRoute: typeof AdminParametrosIndexRoute
}

const AdminParametrosRouteChildren: AdminParametrosRouteChildren = {
  AdminParametrosCatalogosRoute: AdminParametrosCatalogosRoute,
  AdminParametrosCorrelativosRoute: AdminParametrosCorrelativosRoute,
  AdminParametrosUnidadesMedidaRoute: AdminParametrosUnidadesMedidaRoute,
  AdminParametrosIndexRoute: AdminParametrosIndexRoute,
}

const AdminParametrosRouteWithChildren = AdminParametrosRoute._addFileChildren(
  AdminParametrosRouteChildren,
)

interface AdminRecursosHumanosRouteChildren {
  AdminRecursosHumanosCargosRoute: typeof AdminRecursosHumanosCargosRoute
  AdminRecursosHumanosEmpleadosRoute: typeof AdminRecursosHumanosEmpleadosRoute
  AdminRecursosHumanosEspecialidadesRoute: typeof AdminRecursosHumanosEspecialidadesRoute
  AdminRecursosHumanosJerarquiaRoute: typeof AdminRecursosHumanosJerarquiaRoute
  AdminRecursosHumanosMedicosRoute: typeof AdminRecursosHumanosMedicosRoute
  AdminRecursosHumanosProfesionesRoute: typeof AdminRecursosHumanosProfesionesRoute
  AdminRecursosHumanosIndexRoute: typeof AdminRecursosHumanosIndexRoute
}

const AdminRecursosHumanosRouteChildren: AdminRecursosHumanosRouteChildren = {
  AdminRecursosHumanosCargosRoute: AdminRecursosHumanosCargosRoute,
  AdminRecursosHumanosEmpleadosRoute: AdminRecursosHumanosEmpleadosRoute,
  AdminRecursosHumanosEspecialidadesRoute:
    AdminRecursosHumanosEspecialidadesRoute,
  AdminRecursosHumanosJerarquiaRoute: AdminRecursosHumanosJerarquiaRoute,
  AdminRecursosHumanosMedicosRoute: AdminRecursosHumanosMedicosRoute,
  AdminRecursosHumanosProfesionesRoute: AdminRecursosHumanosProfesionesRoute,
  AdminRecursosHumanosIndexRoute: AdminRecursosHumanosIndexRoute,
}

const AdminRecursosHumanosRouteWithChildren =
  AdminRecursosHumanosRoute._addFileChildren(AdminRecursosHumanosRouteChildren)

interface AdminSeguridadRouteChildren {
  AdminSeguridadRolesRoute: typeof AdminSeguridadRolesRoute
  AdminSeguridadUsuariosRoute: typeof AdminSeguridadUsuariosRoute
  AdminSeguridadIndexRoute: typeof AdminSeguridadIndexRoute
}

const AdminSeguridadRouteChildren: AdminSeguridadRouteChildren = {
  AdminSeguridadRolesRoute: AdminSeguridadRolesRoute,
  AdminSeguridadUsuariosRoute: AdminSeguridadUsuariosRoute,
  AdminSeguridadIndexRoute: AdminSeguridadIndexRoute,
}

const AdminSeguridadRouteWithChildren = AdminSeguridadRoute._addFileChildren(
  AdminSeguridadRouteChildren,
)

interface AdminRouteChildren {
  AdminAtencionesRoute: typeof AdminAtencionesRouteWithChildren
  AdminLaboratorioRoute: typeof AdminLaboratorioRouteWithChildren
  AdminParametrosRoute: typeof AdminParametrosRouteWithChildren
  AdminRecursosHumanosRoute: typeof AdminRecursosHumanosRouteWithChildren
  AdminSeguridadRoute: typeof AdminSeguridadRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsuariosPerfilRoute: typeof AdminUsuariosPerfilRoute
  AdminCatalogosIndexRoute: typeof AdminCatalogosIndexRoute
  AdminPacientesIndexRoute: typeof AdminPacientesIndexRoute
  AdminPersonasIndexRoute: typeof AdminPersonasIndexRoute
  AdminRolesIndexRoute: typeof AdminRolesIndexRoute
  AdminUsuariosIndexRoute: typeof AdminUsuariosIndexRoute
  AdminWorkflowIndexRoute: typeof AdminWorkflowIndexRoute
  AdminWorkflowDesignerDefinitionIdRoute: typeof AdminWorkflowDesignerDefinitionIdRoute
  AdminWorkflowInstancesInstanceIdRoute: typeof AdminWorkflowInstancesInstanceIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAtencionesRoute: AdminAtencionesRouteWithChildren,
  AdminLaboratorioRoute: AdminLaboratorioRouteWithChildren,
  AdminParametrosRoute: AdminParametrosRouteWithChildren,
  AdminRecursosHumanosRoute: AdminRecursosHumanosRouteWithChildren,
  AdminSeguridadRoute: AdminSeguridadRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsuariosPerfilRoute: AdminUsuariosPerfilRoute,
  AdminCatalogosIndexRoute: AdminCatalogosIndexRoute,
  AdminPacientesIndexRoute: AdminPacientesIndexRoute,
  AdminPersonasIndexRoute: AdminPersonasIndexRoute,
  AdminRolesIndexRoute: AdminRolesIndexRoute,
  AdminUsuariosIndexRoute: AdminUsuariosIndexRoute,
  AdminWorkflowIndexRoute: AdminWorkflowIndexRoute,
  AdminWorkflowDesignerDefinitionIdRoute:
    AdminWorkflowDesignerDefinitionIdRoute,
  AdminWorkflowInstancesInstanceIdRoute: AdminWorkflowInstancesInstanceIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
