<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\Seed\TarifariosSeed.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
    <PackageReference Include="QuestPDF" Version="2026.7.3" />
    <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.17" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Modules\Almacenes\AjusteInventario\Dtos\" />
    <Folder Include="Modules\Almacenes\AjusteInventario\Endpoints\" />
    <Folder Include="Modules\Almacenes\AjusteInventario\Mappers\" />
    <Folder Include="Modules\Almacenes\AjusteInventario\Services\" />
    <Folder Include="Modules\Almacenes\AjusteInventario\Validators\" />
    <Folder Include="Modules\Almacenes\Almacen\Dtos\" />
    <Folder Include="Modules\Almacenes\Almacen\Endpoints\" />
    <Folder Include="Modules\Almacenes\Almacen\Mappers\" />
    <Folder Include="Modules\Almacenes\Almacen\Services\" />
    <Folder Include="Modules\Almacenes\Almacen\Validators\" />
    <Folder Include="Modules\Almacenes\ConsumoInterno\Dtos\" />
    <Folder Include="Modules\Almacenes\ConsumoInterno\Endpoints\" />
    <Folder Include="Modules\Almacenes\ConsumoInterno\Mappers\" />
    <Folder Include="Modules\Almacenes\ConsumoInterno\Services\" />
    <Folder Include="Modules\Almacenes\ConsumoInterno\Validators\" />
    <Folder Include="Modules\Almacenes\Existencia\Dtos\" />
    <Folder Include="Modules\Almacenes\Existencia\Entity\" />
    <Folder Include="Modules\Almacenes\Existencia\Mappers\" />
    <Folder Include="Modules\Almacenes\Existencia\Services\" />
    <Folder Include="Modules\Almacenes\Existencia\Validators\" />
    <Folder Include="Modules\Almacenes\InventarioFisico\Dtos\" />
    <Folder Include="Modules\Almacenes\InventarioFisico\Endpoints\" />
    <Folder Include="Modules\Almacenes\InventarioFisico\Mappers\" />
    <Folder Include="Modules\Almacenes\InventarioFisico\Services\" />
    <Folder Include="Modules\Almacenes\InventarioFisico\Validators\" />
    <Folder Include="Modules\Almacenes\Lote\Dtos\" />
    <Folder Include="Modules\Almacenes\Lote\Endpoints\" />
    <Folder Include="Modules\Almacenes\Lote\Mappers\" />
    <Folder Include="Modules\Almacenes\Lote\Services\" />
    <Folder Include="Modules\Almacenes\Lote\Validators\" />
    <Folder Include="Modules\Almacenes\MovimientoInventario\Dtos\" />
    <Folder Include="Modules\Almacenes\MovimientoInventario\Endpoints\" />
    <Folder Include="Modules\Almacenes\MovimientoInventario\Mappers\" />
    <Folder Include="Modules\Almacenes\MovimientoInventario\Services\" />
    <Folder Include="Modules\Almacenes\MovimientoInventario\Validators\" />
    <Folder Include="Modules\Almacenes\Producto\Dtos\" />
    <Folder Include="Modules\Almacenes\Producto\Endpoints\" />
    <Folder Include="Modules\Almacenes\Producto\Mappers\" />
    <Folder Include="Modules\Almacenes\Producto\Services\" />
    <Folder Include="Modules\Almacenes\Producto\Validators\" />
    <Folder Include="Modules\Almacenes\ReservaStock\Dtos\" />
    <Folder Include="Modules\Almacenes\ReservaStock\Endpoints\" />
    <Folder Include="Modules\Almacenes\ReservaStock\Mappers\" />
    <Folder Include="Modules\Almacenes\ReservaStock\Services\" />
    <Folder Include="Modules\Almacenes\ReservaStock\Validators\" />
    <Folder Include="Modules\Almacenes\TipoMovimientoInventario\Dtos\" />
    <Folder Include="Modules\Almacenes\TipoMovimientoInventario\Endpoints\" />
    <Folder Include="Modules\Almacenes\TipoMovimientoInventario\Mappers\" />
    <Folder Include="Modules\Almacenes\TipoMovimientoInventario\Services\" />
    <Folder Include="Modules\Almacenes\TipoMovimientoInventario\Validators\" />
    <Folder Include="Modules\Almacenes\TransferenciaAlmacen\Dtos\" />
    <Folder Include="Modules\Almacenes\TransferenciaAlmacen\Endpoints\" />
    <Folder Include="Modules\Almacenes\TransferenciaAlmacen\Mappers\" />
    <Folder Include="Modules\Almacenes\TransferenciaAlmacen\Services\" />
    <Folder Include="Modules\Almacenes\TransferenciaAlmacen\Validators\" />
    <Folder Include="Modules\Cajas\ArqueoCaja\Endpoints\" />
    <Folder Include="Modules\Cajas\ArqueoCaja\Mappers\" />
    <Folder Include="Modules\Cajas\ArqueoCaja\Services\" />
    <Folder Include="Modules\Cajas\ArqueoCaja\Validators\" />
    <Folder Include="Modules\Cajas\Caja\Dtos\" />
    <Folder Include="Modules\Cajas\Caja\Endpoints\" />
    <Folder Include="Modules\Cajas\Caja\Mappers\" />
    <Folder Include="Modules\Cajas\Caja\Services\" />
    <Folder Include="Modules\Cajas\Caja\Validators\" />
    <Folder Include="Modules\Cajas\Cobro\Dtos\" />
    <Folder Include="Modules\Cajas\Cobro\Endpoints\" />
    <Folder Include="Modules\Cajas\Cobro\Mappers\" />
    <Folder Include="Modules\Cajas\Cobro\Rules\" />
    <Folder Include="Modules\Cajas\Cobro\Services\" />
    <Folder Include="Modules\Cajas\Cobro\Validators\" />
    <Folder Include="Modules\Cajas\DevolucionCobro\Dtos\" />
    <Folder Include="Modules\Cajas\DevolucionCobro\Endpoints\" />
    <Folder Include="Modules\Cajas\DevolucionCobro\Mappers\" />
    <Folder Include="Modules\Cajas\DevolucionCobro\Services\" />
    <Folder Include="Modules\Cajas\DevolucionCobro\Validators\" />
    <Folder Include="Modules\Cajas\MovimientoCaja\Dtos\" />
    <Folder Include="Modules\Cajas\MovimientoCaja\Endpoints\" />
    <Folder Include="Modules\Cajas\MovimientoCaja\Mappers\" />
    <Folder Include="Modules\Cajas\MovimientoCaja\Services\" />
    <Folder Include="Modules\Cajas\MovimientoCaja\Validators\" />
    <Folder Include="Modules\Cajas\TurnoCaja\Dtos\" />
    <Folder Include="Modules\Cajas\TurnoCaja\Endpoints\" />
    <Folder Include="Modules\Cajas\TurnoCaja\Mappers\" />
    <Folder Include="Modules\Cajas\TurnoCaja\Services\" />
    <Folder Include="Modules\Farmacia\" />
    <Folder Include="Modules\Parametros\Banco\Dtos\" />
    <Folder Include="Modules\Parametros\Banco\Endpoints\" />
    <Folder Include="Modules\Parametros\Banco\Mappers\" />
    <Folder Include="Modules\Parametros\Banco\Services\" />
    <Folder Include="Modules\Parametros\Banco\Validators\" />
    <Folder Include="Modules\Parametros\Catalogo\Validators\" />
    <Folder Include="Modules\Parametros\MetodoPago\Dtos\" />
    <Folder Include="Modules\Parametros\MetodoPago\Endpoints\" />
    <Folder Include="Modules\Parametros\MetodoPago\Mappers\" />
    <Folder Include="Modules\Parametros\MetodoPago\Services\" />
    <Folder Include="Modules\Parametros\MetodoPago\Validators\" />
    <Folder Include="Modules\Recepcion\Admision\Dtos\" />
    <Folder Include="Modules\Recepcion\Admision\Endpoints\" />
    <Folder Include="Modules\Recepcion\Admision\Services\" />
    <Folder Include="Modules\Recepcion\Admision\Validators\" />
    <Folder Include="Modules\Recepcion\Directorio\Dtos\" />
    <Folder Include="Modules\Recepcion\Directorio\Endpoints\" />
    <Folder Include="Modules\Recepcion\Directorio\Entity\" />
    <Folder Include="Modules\Recepcion\Directorio\Enums\" />
    <Folder Include="Modules\Recepcion\Directorio\Mappers\" />
    <Folder Include="Modules\Recepcion\Directorio\Services\" />
    <Folder Include="Modules\Recepcion\Directorio\Validators\" />
    <Folder Include="Modules\RecursosHumanos\Especialidad\Dtos\" />
    <Folder Include="Modules\RecursosHumanos\Especialidad\Endpoints\" />
    <Folder Include="Modules\RecursosHumanos\Especialidad\Mappers\" />
    <Folder Include="Modules\RecursosHumanos\Especialidad\Services\" />
    <Folder Include="Modules\RecursosHumanos\Especialidad\Validators\" />
    <Folder Include="Modules\RecursosHumanos\Medico\Dtos\" />
    <Folder Include="Modules\RecursosHumanos\Medico\Endpoints\" />
    <Folder Include="Modules\RecursosHumanos\Medico\Mappers\" />
    <Folder Include="Modules\RecursosHumanos\Medico\Services\" />
    <Folder Include="Modules\RecursosHumanos\Medico\Validators\" />
    <Folder Include="Modules\Servicios\Convenios\Dtos\" />
    <Folder Include="Modules\Servicios\Convenios\Endpoints\" />
    <Folder Include="Modules\Servicios\Convenios\Mappers\" />
    <Folder Include="Modules\Servicios\Convenios\Services\" />
    <Folder Include="Modules\Servicios\Convenios\Validators\" />
    <Folder Include="Modules\Servicios\Servicios\Dtos\" />
    <Folder Include="Modules\Servicios\Servicios\Endpoints\" />
    <Folder Include="Modules\Servicios\Servicios\Mappers\" />
    <Folder Include="Modules\Servicios\Servicios\Services\" />
    <Folder Include="Modules\Servicios\Tarifas\Endpoints\" />
    <Folder Include="Modules\Servicios\Tarifas\Mappers\" />
    <Folder Include="Modules\Servicios\Tarifas\Services\" />
    <Folder Include="Modules\Ventas\Venta\Dtos\" />
    <Folder Include="Modules\Ventas\Venta\Endpoints\" />
    <Folder Include="Modules\Ventas\Venta\Services\" />
    <Folder Include="Modules\Ventas\Venta\Validators\" />
  </ItemGroup>

</Project>
