<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
    <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.17" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Modules\Almacen\" />
    <Folder Include="Modules\Farmacia\" />
    <Folder Include="Modules\Parametros\Correlativo\Dtos\" />
    <Folder Include="Modules\Parametros\Correlativo\Endpoints\" />
    <Folder Include="Modules\Parametros\Correlativo\Mappers\" />
    <Folder Include="Modules\Parametros\Correlativo\Services\" />
    <Folder Include="Modules\Recepcion\Directorio\Dtos\" />
    <Folder Include="Modules\Recepcion\Directorio\Endpoints\" />
    <Folder Include="Modules\Recepcion\Directorio\Entity\" />
    <Folder Include="Modules\Recepcion\Directorio\Mappers\" />
    <Folder Include="Modules\Recepcion\Directorio\Services\" />
    <Folder Include="Modules\Recepcion\Directorio\Validators\" />
    <Folder Include="Modules\RecursosHumanos\Especialidad\Dtos\" />
    <Folder Include="Modules\RecursosHumanos\Especialidad\Endpoints\" />
    <Folder Include="Modules\RecursosHumanos\Especialidad\Mappers\" />
    <Folder Include="Modules\RecursosHumanos\Especialidad\Services\" />
    <Folder Include="Modules\RecursosHumanos\Especialidad\Validators\" />
    <Folder Include="Modules\RecursosHumanos\Medico\Dtos\" />
    <Folder Include="Modules\RecursosHumanos\Medico\Endpoints\" />
    <Folder Include="Modules\RecursosHumanos\Medico\Mappers\" />
    <Folder Include="Modules\RecursosHumanos\Medico\Services\" />
    <Folder Include="Modules\RecursosHumanos\Medico\Validators\" />
    <Folder Include="Modules\Servicios\Convenios\Dtos\" />
    <Folder Include="Modules\Servicios\Convenios\Endpoints\" />
    <Folder Include="Modules\Servicios\Convenios\Mappers\" />
    <Folder Include="Modules\Servicios\Convenios\Services\" />
    <Folder Include="Modules\Servicios\Convenios\Validators\" />
    <Folder Include="Modules\Servicios\Servicios\Dtos\" />
    <Folder Include="Modules\Servicios\Servicios\Endpoints\" />
    <Folder Include="Modules\Servicios\Servicios\Mappers\" />
    <Folder Include="Modules\Servicios\Servicios\Services\" />
    <Folder Include="Modules\Servicios\Tarifas\Dtos\" />
    <Folder Include="Modules\Servicios\Tarifas\Endpoints\" />
    <Folder Include="Modules\Servicios\Tarifas\Mappers\" />
    <Folder Include="Modules\Servicios\Tarifas\Services\" />
    <Folder Include="Modules\Servicios\Tarifas\Validators\" />
  </ItemGroup>

</Project>
